### PR TITLE
added popout to chat menu

### PR DESCRIPTION
**Pull request by urbit-pilled**
/claim #80 

https://github.com/user-attachments/assets/cabdf81c-892a-46e6-82ac-c3ef8dfa7370

### CODE REVIEW

**Comment by zcesur** [comment]
Thanks for the PR @urbit-pilled!

Can we make the chatbox adapt to the size of the window instead of fixing it at 400x400? Streamers usually use these full height. We also need a chat input so they can send messages

Let's not overwrite `AlgoraWeb.ChatLive` though since we use that as an OBS overlay (which should be fixed in size and without an input)

**Comment by urbit-pilled** [comment]
sorry for the long delay, I have some free time now so I can work on issues again.

https://github.com/user-attachments/assets/516cb122-aec2-4b5b-829f-d06276a7e495

**Comment by urbit-pilled** [comment]
@zcesur I have implemented your requests and I believe this is ready for review now

- Chat popout now takes up the full window size 
- Chat popout has an input box so they can send message

**Comment by zcesur** [comment]
Awesome, thanks!

**Pull request merged**
