### PR TITLE
feat(streaming): implement stream key management

### PR DESCRIPTION
**Pull request by onyedikachi-david**
/claim #41
Fixes: #41

- Add RTMP URL and Stream key fields to the streaming form
- Implement reset and copy functionality for stream key
- Add backward compatibility for users without stream keys
- Display toast notification when copying stream key

### CODE REVIEW

**Comment by onyedikachi-david** [comment]
image

**Comment by zcesur** [comment]
Thank you for the changes, will review shortly!

**Comment by zcesur** [comment]
Getting this error:

```
[error] GenServer #PID<0.882.0> terminating
** (KeyError) key :stream_key not found in: %Membrane.RTMP.Messages.Connect{
  app: "live",
  tc_url: "rtmp://localhost:9006/live",
  flash_version: "FMLE/3.0 (compatible; FMSc/1.0)",
  swf_url: "rtmp://localhost:9006/live",
  fpad: nil,
  audio_codecs: nil,
  video_codecs: nil,
  video_function: nil,
  page_url: nil,
  object_encoding: nil,
  extra: %{"type" => "nonprivate"},
  tx_id: 1.0
}
```

Pretty sure it should be exposed in a param inside one of the `validate_xyz` handlers

**Comment by zcesur** [comment]
Resolved with another PR, thanks for attempting!

**Pull request closed without merging**
