### PR TITLE
Unmute overlay resolved 

### PR DESCRIPTION
**Pull request by Rushhaabhhh**
/claim #102

### CODE REVIEW

**Comment by Rushhaabhhh** [comment]
WhatsApp Image 2024-11-30 at 17 46 14_391eee69
WhatsApp Image 2024-11-30 at 17 46 24_4ddfe4fd

**Comment by Rushhaabhhh** [comment]
Please review and provide an update on the pull request

**Comment by lastcanal** [comment]
Hello @Rushhaabhhh, your unmute overlay is not working for me. It is throwing a `FunctionClauseError`, causing the socket to disconnect. Unfortunately this leaves the player controls blocked by the overlay, not allowing me to unmute the video at all. You can see that a faint unmute icon remains.

Screenshot from 2024-12-12 14-12-23

When you get a chance to look at this, would you mind rebasing against the `dev` branch? i see you are relying on `parentElement` in your JS code, and that element might be different now.

**Comment by Rushhaabhhh** [comment]
@lastcanal Sure, I'll check on it and provide an update once it's completed.

**Comment by zcesur** [comment]
Closing this in favor of #125, thanks for attempting!

**Pull request closed without merging**
